import type { Metadata } from "next";
import { Poppins, Ovo } from "next/font/google";
import "./globals.css";


const outfitFont = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: '500',
});

const ovoFont = Ovo({
  variable: "--font-ovo",
  subsets: ["latin"],
  weight: '400',
});


export const metadata: Metadata = {
  title: "Portfolio Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="font-sans">
      <body
        className={`${outfitFont.variable} ${ovoFont.variable} antialiased`}
      >

        {children}
      </body>
    </html>
  );
}
